### PR TITLE
Ryzen support

### PR DESCRIPTION
**Pull request by Waltibaba**
I added a small patch for Ryzen support, using the max of all CPU die temperatures (supports Threadripper multi-die and theoretically EPYC multi-socket too).
Also simplified the removal of the trailing ".0" with an integer cast

### CODE REVIEW

**Comment by Waltibaba** [comment]
psuinfo was crashing on my Threadripper machine because `temp["coretemp"]` is not found on non-Intel platforms, and it couldn't display my cpu temperature.

**Comment by nwg-piotr** [comment]
Can't check on Ryzen, on Intel obviously works well. :)

However, due to improper packaging I used on Arch Linux, merging your PR now would crash installation from AUR. I'll publish a release and do it right way tonight. Thanks for contribution!

**Comment by nwg-piotr** [comment]
If it comes to shebang: for Arch and Void `#!/usr/bin/python3` is proper. I know nothing about packages for other distributions.

**Comment by Waltibaba** [comment]
Sorry, I didn't test the PKGBUILD. I'm on Arch too, "#!/usr/bin/env python3" is the universal way that works on all distros, and would work with an activated virtualenv or similar too. In contrast, not all distros are guaranteed to package under /usr/bin/python3...
The "env" version works fine for me on vanilla arch and Antergos.

**Comment by nwg-piotr** [comment]
I remember being asked to change the header in both ways. :) Actually, the script is simple enough to be just saved e.g. to ./local/bin and modified to user's taste. On the daily basis I use a version modified for sway / waybar, which uses glyphs instead of icons. I only use Tint2 in Openbox.

**Pull request merged**
